### ISSUE TITLE
Links will be created only from smaller number ids to bigger number ids

### ISSUE THREAD

**Issue by mikami-ais** [hoshizora-project/amanogawa#3]
In to_graph.cpp, links will be created only from smaller number ids to bigger number ids.

If this behavior is not intended, I think "flow" method (lines about 160) should be fixed as
```
-            const auto min = std::min(i, ngh.node_id);
-            const auto max = std::max(i, ngh.node_id);
-            adj_list[min].emplace(max);
+            adj_list[i].emplace(ngh.node_id);
```

**Comment by amaya382** [comment]
@mikami-ais Thank you for a bug report
This logic removes duplicated edges in *undirected graphs*. Current all measures are for undirected graph so it is intended.
But we have to impl another logic for directed graphs. I'll work on it in the future.
